patch:
  tags:
  - catalogs
  summary: Update extraction config of catalog
  description: Updates extraction config of catalog
  operationId: async_extraction_config
  parameters:
  - name: x-correlation-id
    in: header
    description: correlation id to track requests
    schema:
      type: string
  - required: true
    schema:
      title: Catalog Id
      type: string
    name: catalog_id
    in: path
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/CatalogAsyncExtractionConfigIn.yaml"

  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            allOf:
             - $ref: '../../schemas/CatalogAsyncSchemaOut.yaml'

    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '../../schemas/PostFailureResponse.yaml'
    '422':
      description: Validation Error
      content:
        application/json:
          schema:
            $ref: '../../schemas/HTTPValidationError.yaml'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '../../schemas/PostFailureResponse.yaml'
