properties:
  created_ts:
    description: This field describes the initial date of creation of the dataset.
    title: Created Ts
    type: string
  display_name:
    description: This field describes the display name of the node type. This is used
      in the UI to display the node type.
    title: Display Name
    type: string
  group:
    allOf:
    - $ref: ../workflows/NodeTypeGroup.yaml
    description: This field describes the group of the node type. This is used in
      the UI to display the node type.
    title: Group
  icon:
    description: This field describes the icon of the node type. This is used in the
      UI to display the node type.
    title: Icon
    type: string
  icon_type:
    description: This field describes the icon type of the node type. This is used
      in the UI to display the node type.
    title: Icon Type
    type: string
  schema:
    description: This field describes the schema of the node type. This is used in
      the UI to display the node type.
    title: Schema
    type: object
  type:
    description: This field describes the type of the node. The node can be a dataset
      node, transformation node in data workflows, model training / artifact / inference
      nodes in machine learning workflows and so on.
    title: Type
    type: string
  type_id:
    description: This field describes the identifier of the node type.
    title: Type Id
    type: string
  updated_ts:
    description: This field describes the latest date of updation of the dataset.
    title: Updated Ts
    type: string
required:
- created_ts
- updated_ts
- type_id
- type
- display_name
- icon
title: NodeTypeConfigValidation
type: object
