get:
  description: Get the status of a running ingress
  operationId: get_ingress_run_status_api_v2_connectors_ingress__ingress_id__run__run_id__status_get
  parameters:
  - description: correlation id to track requests
    in: header
    name: x-correlation-id
    schema:
      type: string
  - in: path
    name: ingress_id
    required: true
    schema:
      title: Ingress Id
      type: string
  - in: path
    name: run_id
    required: true
    schema:
      title: Run Id
      type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../../schemas/connectors_hub/GetIngressRunStatusResponse.yaml
      description: Successful Response
    '422':
      content:
        application/json:
          schema:
            $ref: ../../schemas/connectors_hub/HTTPValidationError.yaml
      description: Validation Error
  summary: Get Ingress Run Status
  tags:
  - connectors
