post:
  operationId: update_feature_values_api_v1_features_v2_feature_values_post
  parameters:
  - description: correlation id to track requests
    in: header
    name: x-correlation-id
    schema:
      type: string
  responses:
    '200':
      content:
        application/json:
          schema: {}
      description: Successful Response
  summary: Update Feature Values
  tags:
  - Features
